### ISSUE TITLE
Cached size is not updated

### ISSUE THREAD

**Issue by kelunik** [amphp/http-server-static-content#7]
The cached size of files is not updated. If files are changed, this might result in a wrong content-length header.

**Comment by minbaby** [comment]
I think this bug is because of `amphp/file`.

 `StatCache` cache the file state,  but not update file state when file info changed.

https://github.com/amphp/http-server-static-content/blob/a66a58a9b3263be5ddda7ee129831ce603358651/src/DocumentRoot.php#L225

https://github.com/amphp/http-server-static-content/blob/a66a58a9b3263be5ddda7ee129831ce603358651/src/DocumentRoot.php#L208

https://github.com/amphp/file/blob/cc1d11993e1546e4cad9bd2de22c6ba8ff88af3c/lib/UvDriver.php#L115

https://github.com/amphp/file/blob/cc1d11993e1546e4cad9bd2de22c6ba8ff88af3c/lib/StatCache.php#L19

**Comment by bwoebi** [comment]
So, setting `StatCache::ttl(0);` in your server does fix it?

Generally the StatCache is a good thing, reducing latency by a good margin...
We possibly should add a file change watcher (i/anotify for example) for stat invalidation ...

**Comment by minbaby** [comment]
Yeah, we need inotify extension.  if has `inotify`, all the thing can bu resolved.

This is two reason，first is StatCache, another is cache too.
We can't get the file stat on file changed.   if We have not `inodify`，only update file info in every seconds

https://github.com/amphp/http-server-static-content/blob/a66a58a9b3263be5ddda7ee129831ce603358651/src/DocumentRoot.php#L144
